CREATE DATABASE Chama_JussaDB

USE Chama_JussaDB;

CREATE TABLE UsuarioTB(
	IdUsuario UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,

	Nome NVARCHAR(160) NOT NULL,
	Senha NVARCHAR(40) NOT NULL,
	Imagem NVARCHAR(200) NOT NULL,
	Email NVARCHAR(255) NOT NULL UNIQUE,
);

CREATE TABLE ServicoTB(
	IdServico UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	IdUsuario UNIQUEIDENTIFIER NOT NULL,


	Titulo NVARCHAR (255) NOT NULL,
	Maquina NVARCHAR (255) NOT NULL,
	Localização NVARCHAR (255) NOT NULL,
	Descricao NVARCHAR (255) NOT NULL,
	Imagem NVARCHAR (200),
	Numero_Servico INT IDENTITY(1,1) NOT NULL,
	Situacao NVARCHAR (255) NOT NULL,
	Data_Criacao DATETIME NOT NULL DEFAULT GETUTCDATE(),

	FOREIGN KEY (IdUsuario) REFERENCES UsuarioTB(IdUsuario)
);

CREATE TABLE NotificacaoTB(
	IdNotificacao UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	IdUsuario UNIQUEIDENTIFIER NOT NULL,
	IdServico UNIQUEIDENTIFIER NOT NULL,

	Mensagem NVARCHAR (255) NOT NULL,
	Data_Hora DATETIME NOT NULL DEFAULT GETUTCDATE(),

	FOREIGN KEY (IdUsuario) REFERENCES UsuarioTB(IdUsuario),
	FOREIGN KEY (IdServico) REFERENCES ServicoTB(IdServico)
);
